# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/main/schema/markdownlint-cli2-config-schema.json

globs:
  - "**/*.md"

ignores:
  - node_modules/
  - target/

# Rules: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
config:
  default: true
  line-length: false
  first-line-heading: false
