[package]
name = "akv-cli"
version = "0.5.0"
edition = "2021"
description = """
The Azure Key Vault CLI can be used to read secrets, pass them securely to other commands,
or inject them into configuration files.
"""
authors = ["Heath Stewart (https://github.com/heaths)"]
repository = "https://github.com/heaths/akv-cli-rs"
license = "MIT"
rust-version = "1.85"

[features]
debug = ["azure_core/debug"]

[dependencies]
async-lock = "3.4.0"
async-stream = "0.3.6"
async-trait = "0.1.88"
azure_core = "0.25.0"
azure_identity = "0.25.0"
azure_security_keyvault_keys = "0.4.0"
azure_security_keyvault_secrets = "0.4.0"
clap = { version = "4.5.28", features = ["derive", "env"] }
clap_complete = "4.5.46"
dotazure = "0.2.0"
dotenvy = "0.15.7"
futures = "0.3.31"
libc = "0.2.171"
once_cell = "1.21.3"
openssl = "0.10.72"
prettytable-rs = "0.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
time = "0.3.37"
timeago = "0.4.2"
tokio = { version = "1.43.0", features = [
    "macros",
    "rt",
] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "local-time",
] }
url = "2.5.4"

[dev-dependencies]
anstream = "0.6.18"
anstyle = "1.0.10"
async-trait = "0.1.88"
criterion = "0.6.0"

[profile.release]
opt-level = "s"
panic = "abort"
strip = "debuginfo"

[[bench]]
name = "jwe"
harness = false
