[package]
name = "akv-cli"
version = "0.1.1"
edition = "2021"
description = """
The Azure Key Vault CLI can be used to read secrets, pass them securely to other commands,
or inject them into configuration files.
"""
authors = ["Heath Stewart (https://github.com/heaths)"]
repository = "https://github.com/heaths/akv-cli-rs"
license = "MIT"
rust-version = "1.80"

[dependencies]
async-stream = "0.3.6"
azure_core = "0.22.0"
azure_identity = "0.22.0"
azure_security_keyvault_secrets = "0.1.0"
clap = { version = "4.5.28", features = ["derive", "env"] }
dotenvy = "0.15.7"
futures = "0.3.31"
prettytable-rs = "0.10.0"
time = "0.3.37"
timeago = "0.4.2"
tokio = { version = "1.43.0", features = [
    "io-std",
    "macros",
    "process",
    "rt",
] }
tokio-util = { version = "0.7.13", features = ["codec"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
url = "2.5.4"

[dev-dependencies]
anstream = "0.6.18"
anstyle = "1.0.10"

[profile.release]
opt-level = "s"
panic = "abort"
strip = "debuginfo"

[[bin]]
name = "akv"
path = "src/main.rs"
