[tageet.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# When cross-compiling on aarch64, need to set:
# PKG_CONFIG_SYSROOT_DIR=/usr/lib/x86_64-linux-gnu
[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
