name: live

on:
  workflow_dispatch:
    inputs:
      release:
        description: Build release
        required: false
        type: boolean
        default: false
      clean:
        description: Delete resources
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install azd
      uses: Azure/setup-azd@v2
    - name: Cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Set up toolchain
      run: rustup install
    - name: Authentication az (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    - name: Authenticate azd (OIDC)
      run: >
        azd auth login
        --client-id "${env:AZURE_CLIENT_ID}"
        --federated-credential-provider "github"
        --tenant-id "${env:AZURE_TENANT_ID}"
      shell: pwsh
    - name: Provision
      run: azd provision --no-prompt
    - name: Install Pester
      run: |
        Install-Module Pester -RequiredVersion 5.6.1 -Force -Scope CurrentUser
        Import-Module Pester -RequiredVersion 5.6.1
      shell: pwsh
    - name: Test
      run: |
        Import-Module Pester -RequiredVersion 5.6.1
        $config = New-PesterConfiguration
        $config.Run.Path = 'tests/'
        $config.Run.Parameters = @{ Release = ('${{ inputs.release }}' -eq 'true') }
        $config.Output.Verbosity = 'Detailed'
        Invoke-Pester -Configuration $config
      shell: pwsh
    - name: Clean
      if: inputs.clean
      run: azd down --force --purge --no-prompt
